// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_lwgeom_version
std::string get_lwgeom_version();
RcppExport SEXP _Rliblwgeom_get_lwgeom_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_lwgeom_version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rliblwgeom_get_lwgeom_version", (DL_FUNC) &_Rliblwgeom_get_lwgeom_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rliblwgeom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
